# Generated by Django 4.1.7 on 2023-02-26 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_login'),
    ]

    operations = [
        migrations.DeleteModel(
            name='login',
        ),
    ]
